package register

import (
	"crypto/x509"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// AuthzRoleDef is a role entry for generating authz.json (compatible with core Policy.RoleDef).
type AuthzRoleDef struct {
	DisplayName string   `json:"display_name"`
	Profiles    []string `json:"profiles"`
	Grants      []string `json:"grants"`
	Scope       []string `json:"scope,omitempty"`
}

// GatewayNSDef is a gateway namespace entry for generating authz.json.
type GatewayNSDef struct {
	DisplayName string   `json:"display_name"`
	Prefix      string   `json:"prefix"`
	Grants      []string `json:"grants"`
}

// AuthzDocument is the complete authz.json document generated by gen-authz.
// The top-level structure is compatible with core/auth.Policy; capability_parameters is an extension field
// (core's encoding/json deserialization ignores unknown fields).
type AuthzDocument struct {
	Version              string                    `json:"version"`
	Roles                map[string]AuthzRoleDef   `json:"roles"`
	OUMapping            map[string]string         `json:"ou_mapping"`
	GatewayNamespaces    map[string]GatewayNSDef   `json:"gateway_namespaces,omitempty"`
	CapabilityParameters map[string]map[string]any `json:"capability_parameters,omitempty"`
}

// GenAuthzConfig is the input configuration for GenAuthz.
type GenAuthzConfig struct {
	// SchemePaths is the list of capability.json file paths to merge.
	// The primary scheme (providing roles) must be the first; other schemes only contribute capability catalogs.
	SchemePaths []string
	// When VerifySignature is true, enforce signature verification if .p7s exists; fail on error.
	// Files without .p7s only error when VerifyRequired is true.
	VerifySignature bool
	// When VerifyRequired is true, capability files missing .p7s signature fail immediately.
	VerifyRequired bool
	// TrustRootsPEM is the trust root certificates for signature verification (PEM file paths).
	TrustRootsPEM []string
	// Version is the generated authz.json version field (default "v2").
	Version string
	// NamespacePrefix is appended to role names to generate gateway namespace prefix role grants,
	// e.g. "gateway" → gateway_namespaces["gateway:"].
	// By default, extracts the "gateway:xxx" prefix from all Roles in the primary scheme.
	NamespacePrefix string
}

// GenAuthz generates an authz.json document from capability.json schemes.
//
// Mapping rules:
//   - Roles from the primary scheme (first) become authz.json roles (grants preserved as-is)
//   - Each role's OUs are expanded into ou_mapping (OU → role name)
//   - Role names with namespace prefixes (e.g. gateway:admin) are aggregated into gateway_namespaces
//   - Capability parameter defaults from all schemes are aggregated into capability_parameters
func GenAuthz(cfg GenAuthzConfig) (*AuthzDocument, error) {
	if len(cfg.SchemePaths) == 0 {
		return nil, fmt.Errorf("gen-authz: no scheme paths given")
	}
	if cfg.Version == "" {
		cfg.Version = "v2"
	}

	doc := &AuthzDocument{
		Version:              cfg.Version,
		Roles:                make(map[string]AuthzRoleDef),
		OUMapping:            make(map[string]string),
		GatewayNamespaces:    make(map[string]GatewayNSDef),
		CapabilityParameters: make(map[string]map[string]any),
	}

	// Trust roots
	var trustRoots []string
	trustRoots = append(trustRoots, cfg.TrustRootsPEM...)

	// First pass: load all schemes + verify signatures
	var defs []*SchemeDefinition
	for i, p := range cfg.SchemePaths {
		def, err := LoadScheme(p)
		if err != nil {
			return nil, fmt.Errorf("gen-authz: load %s: %w", p, err)
		}
		hasSig := HasSignature(p)
		if cfg.VerifyRequired && !hasSig {
			return nil, fmt.Errorf("gen-authz: %s has no .p7s signature (verify-required)", p)
		}
		if hasSig && (cfg.VerifySignature || cfg.VerifyRequired) {
			var roots []*x509.Certificate
			for _, rp := range trustRoots {
				certs, err := LoadCertFile(rp)
				if err != nil {
					return nil, fmt.Errorf("gen-authz: trust root %s: %w", rp, err)
				}
				roots = append(roots, certs...)
			}
			if err := VerifyCapabilityPKCS7(p, roots); err != nil {
				return nil, fmt.Errorf("gen-authz: signature of %s: %w", p, err)
			}
		}
		// Role validation: strict for primary scheme, secondary schemes only check self-consistency
		errs, warns := def.ValidateSchemeRoles()
		for _, w := range warns {
			fmt.Fprintf(os.Stderr, "gen-authz: warn: %s\n", w)
		}
		if len(errs) > 0 {
			var sb strings.Builder
			for _, e := range errs {
				sb.WriteString("\n  - ")
				sb.WriteString(e.Error())
			}
			return nil, fmt.Errorf("gen-authz: invalid roles in %s:%s", p, sb.String())
		}
		// Collect parameter defaults
		for _, cap := range def.Capabilities {
			if len(cap.Parameters) == 0 {
				continue
			}
			params := make(map[string]any)
			for k, pd := range cap.Parameters {
				if pd.Default != nil {
					params[k] = pd.Default
				}
			}
			if len(params) > 0 {
				fullID := def.SchemeID + ":" + cap.ID
				doc.CapabilityParameters[fullID] = params
			}
		}
		if i == 0 {
			defs = append([]*SchemeDefinition{def}, defs...) // main
		} else {
			defs = append(defs, def)
		}
	}

	// Primary scheme roles
	main := defs[0]
	prefixes := make(map[string]bool)
	// Aggregate namespace prefixes from all scheme role names (e.g. gateway:admin → "gateway:")
	for _, def := range defs {
		for role := range def.Roles {
			if idx := strings.Index(role, ":"); idx > 0 {
				prefixes[role[:idx+1]] = true
			}
		}
	}
	for role, rd := range main.Roles {
		authzRole := AuthzRoleDef{
			DisplayName: rd.DisplayName,
			Profiles:    rd.Profiles,
			Grants:      rd.Grants,
		}
		doc.Roles[role] = authzRole
		// OU mapping
		for _, ou := range rd.OUs {
			doc.OUMapping[ou] = role
		}
	}
	// Aggregate gateway_namespaces
	if cfg.NamespacePrefix != "" {
		prefixes[cfg.NamespacePrefix] = true
	}
	if len(prefixes) > 0 {
		keys := make([]string, 0, len(prefixes))
		for k := range prefixes {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, prefix := range keys {
			nsGrants := []string{prefix + "*"}
			doc.GatewayNamespaces[prefix] = GatewayNSDef{
				DisplayName: "命名空间 " + prefix,
				Prefix:      prefix,
				Grants:      nsGrants,
			}
		}
	}

	return doc, nil
}

// GenAuthzToFile generates and writes the authz.json file.
func GenAuthzToFile(cfg GenAuthzConfig, outputPath string) error {
	doc, err := GenAuthz(cfg)
	if err != nil {
		return err
	}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return fmt.Errorf("gen-authz: marshal: %w", err)
	}
	if err := os.WriteFile(outputPath, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("gen-authz: write %s: %w", outputPath, err)
	}
	return nil
}
